
namespace robokins
{
    partial class Bot
    {
        struct Commands
        {
            #region Names
            public static readonly string[] Names = new string[] { 
                "#AllowSameLineComments",
                "#ClipboardTimeout",
                "#CommentFlag",
                "#Delimiter",
                "#DerefChar",
                "#ErrorStdOut",
                "#EscapeChar",
                "#HotkeyInterval",
                "#HotkeyModifierTimeout",
                "#Hotstring",
                "#IfWinActive",
                "#IfWinExist",
                "#Include",
                "#IncludeAgain",
                "#InstallKeybdHook",
                "#InstallMouseHook",
                "#KeyHistory",
                "#LTrim",
                "#MaxHotkeysPerInterval",
                "#MaxMem",
                "#MaxThreads",
                "#MaxThreadsBuffer",
                "#MaxThreadsPerHotkey",
                "#NoEnv",
                "#NoTrayIcon",
                "#Persistent",
                "#SingleInstance",
                "#UseHook",
                "#WinActivateForce",
                ":=",
                "{Blind}",
                "A_AhkPath",
                "A_AhkVersion",
                "A_AppData",
                "A_AppDataCommon",
                "A_AutoTrim",
                "A_BatchLines",
                "A_CaretX",
                "A_CaretY",
                "A_ComputerName",
                "A_ControlDelay",
                "A_Cursor",
                "A_DD",
                "A_DDD",
                "A_DDDD",
                "A_DefaultMouseSpeed",
                "A_Desktop",
                "A_DesktopCommon",
                "A_DetectHiddenText",
                "A_DetectHiddenWindows",
                "A_EndChar",
                "A_EventInfo",
                "A_ExitReason",
                "A_FormatFloat",
                "A_FormatInteger",
                "A_Gui",
                "A_GuiControl",
                "A_GuiControlEvent",
                "A_GuiEvent",
                "A_GuiHeight",
                "A_GuiWidth",
                "A_GuiX",
                "A_GuiY",
                "A_Hour",
                "A_IconFile",
                "A_IconHidden",
                "A_IconNumber",
                "A_IconTip",
                "A_Index",
                "A_IPAddress1 through 4",
                "A_IsAdmin",
                "A_IsCompiled",
                "A_IsCompiled",
                "A_IsCompiled",
                "A_IsSuspended",
                "A_KeyDelay",
                "A_Language",
                "A_Language Values",
                "A_LastError",
                "A_LineFile",
                "A_LineNumber",
                "A_LoopField",
                "A_LoopFileAttrib",
                "A_LoopFileDir",
                "A_LoopFileExt",
                "A_LoopFileFullPath",
                "A_LoopFileLongPath",
                "A_LoopFileName",
                "A_LoopFileShortName",
                "A_LoopFileShortPath",
                "A_LoopFileSize",
                "A_LoopFileSizeKB",
                "A_LoopFileSizeMB",
                "A_LoopFileTimeAccessed",
                "A_LoopFileTimeCreated",
                "A_LoopFileTimeModified",
                "A_LoopReadLine",
                "A_LoopRegKey",
                "A_LoopRegName",
                "A_LoopRegSubKey",
                "A_LoopRegTimeModified",
                "A_LoopRegType",
                "A_MDay",
                "A_Min",
                "A_MM",
                "A_MMM",
                "A_MMMM",
                "A_Mon",
                "A_MouseDelay",
                "A_MSec",
                "A_MyDocuments",
                "A_Now",
                "A_NowUTC",
                "A_NumBatchLines",
                "A_OSType",
                "A_OSVersion",
                "A_PriorHotkey",
                "A_ProgramFiles",
                "A_Programs",
                "A_ProgramsCommon",
                "A_ScreenHeight",
                "A_ScreenWidth",
                "A_ScriptDir",
                "A_ScriptFullPath",
                "A_ScriptName",
                "A_Sec",
                "A_Space",
                "A_StartMenu",
                "A_StartMenuCommon",
                "A_Startup",
                "A_StartupCommon",
                "A_StringCaseSense",
                "A_Tab",
                "A_Temp",
                "A_ThisFunc",
                "A_ThisHotkey",
                "A_ThisLabel",
                "A_ThisMenu",
                "A_ThisMenuItem",
                "A_ThisMenuItemPos",
                "A_TickCount",
                "A_TimeIdle",
                "A_TimeIdlePhysical",
                "A_TimeSincePriorHotkey",
                "A_TimeSinceThisHotkey",
                "A_TitleMatchMode",
                "A_TitleMatchModeSpeed",
                "A_UserName",
                "A_WDay",
                "A_WinDelay",
                "A_WinDir",
                "A_WorkingDir",
                "A_YDay",
                "A_Year",
                "A_YWeek",
                "A_YYYY",
                "abbreviation expansion",
                "Abs()",
                "absolute value, abs()",
                "Acknowledgements",
                "ACos()",
                "activate a window",
                "add",
                "Address of a variable",
                "administrator privileges for scripts",
                "ahk_class",
                "ahk_group",
                "ahk_id",
                "ahk_pid",
                "ahk2exe",
                "AllowSameLineComments",
                "alnum",
                "alpha",
                "AltGr",
                "AltTab",
                "AlwaysOnTop (WinSet)",
                "append to file",
                "Arrays",
                "Asc()",
                "ASCII conversion",
                "ASin()",
                "assigning values to variables",
                "ATan()",
                "attributes of files and folders",
                "auto-execute section",
                "AutoIt v2",
                "auto-replace text as you type it",
                "AutoScriptWriter",
                "AutoTrim",
                "balloon tip",
                "beep the PC speaker",
                "between (check if var between two values)",
                "bitwise operations",
                "blind-mode Send",
                "BlockInput",
                "blocks (lines enclosed in braces)",
                "Break",
                "buffering",
                "built-in functions",
                "built-in variables",
                "Button controls (GUI)",
                "button list (mouse and joystick)",
                "button state",
                "ByRef",
                "callbacks",
                "case sensitive strings",
                "Ceil()",
                "Changelog",
                "Checkbox controls (GUI)",
                "choose file",
                "choose folder",
                "Chr()",
                "class name of a window",
                "Click a mouse button",
                "Clipboard",
                "ClipboardAll",
                "ClipWait",
                "close a window",
                "CLSID List (My Computer, etc.)",
                "color names, RGB/HTML",
                "color of pixels",
                "COM (Component Object Model) via DllCall",
                "ComboBox controls (GUI)",
                "comma operator (multi-statement)",
                "command line parameters",
                "commands, alphabetical list",
                "CommentFlag",
                "comments in scripts",
                "compile a script",
                "Component Object Model (COM) via DllCall",
                "ComSpec",
                "concatenate, in expressions",
                "concatenate, script lines",
                "context menu (GUI)",
                "continuation sections",
                "Continue",
                "Control",
                "ControlClick",
                "ControlFocus",
                "ControlGet",
                "ControlGetFocus",
                "ControlGetPos",
                "ControlGetText",
                "ControlMove",
                "ControlSend",
                "ControlSendRaw",
                "ControlSetText",
                "convert a .aut file to .ahk",
                "convert a script to an EXE",
                "coordinates",
                "CoordMode",
                "copy file",
                "copy folder/directory",
                "Cos()",
                "create file",
                "create folder/directory",
                "Critical",
                "current directory",
                "current thread",
                "cursor shape",
                "dates and times (compare)",
                "dates and times (math)",
                "dates and times (of files)",
                "DateTime controls (GUI)",
                "debugger",
                "debugging a script",
                "decimal places",
                "decompile a compiled script",
                "delete files",
                "delete folder/directory",
                "Delimiter",
                "DerefChar",
                "DetectHiddenText",
                "DetectHiddenWindows",
                "dialog FileSelectFile",
                "dialog FileSelectFolder",
                "dialog InputBox",
                "dialog MsgBox",
                "digit",
                "disk space",
                "divide (math)",
                "DllCall()",
                "download a file",
                "drag and drop (GUI windows)",
                "drag the mouse",
                "Drive",
                "DriveGet",
                "DriveSpaceFree",
                "DropDownList controls (GUI)",
                "Edit",
                "Edit controls (GUI)",
                "Else",
                "EndRepeat",
                "EnvAdd",
                "EnvDiv",
                "EnvGet",
                "environment variables",
                "environment variables (change them)",
                "EnvMult",
                "EnvSet",
                "EnvSub",
                "EnvUpdate",
                "ErrorLevel",
                "ErrorStdOut",
                "escape sequence",
                "EscapeChar",
                "Exe2Ahk",
                "Exit",
                "ExitApp",
                "Exp()",
                "expressions",
                "ExtractInteger -&gt; NumGet()",
                "FAQ (Frequently Asked Questions)",
                "file attributes",
                "file or folder (does it exist)",
                "file pattern",
                "file, creating",
                "file, reading",
                "file, writing/appending",
                "FileAppend",
                "FileCopy",
                "FileCopyDir",
                "FileCreateDir",
                "FileCreateShortcut",
                "FileDelete",
                "FileExist()",
                "FileGetAttrib",
                "FileGetShortcut",
                "FileGetSize",
                "FileGetTime",
                "FileGetVersion",
                "FileInstall",
                "FileMove",
                "FileMoveDir",
                "FileRead",
                "FileReadLine",
                "FileRecycle",
                "FileRecycleEmpty",
                "FileRemoveDir",
                "FileSelectFile",
                "FileSelectFolder",
                "FileSetAttrib",
                "FileSetTime",
                "find a file",
                "find a string",
                "find a window",
                "floating point (check if it is one)",
                "floating point (SetFormat)",
                "Floor()",
                "focus",
                "folder/directory copy",
                "folder/directory create",
                "folder/directory move",
                "folder/directory remove",
                "folder/directory select",
                "Fonts",
                "format, numbers",
                "FormatTime",
                "free space",
                "FTP uploading example",
                "functions (defining and calling)",
                "Functions (libraries)",
                "game automation",
                "GetKeyState",
                "GetKeyState()",
                "g-label (responding to GUI events)",
                "global variables in functions",
                "Gosub",
                "Goto",
                "GroupActivate",
                "GroupAdd",
                "GroupBox controls (GUI)",
                "GroupClose",
                "GroupDeactivate",
                "Gui",
                "Gui control types",
                "Gui styles reference",
                "GuiClose (label)",
                "GuiContextMenu (label)",
                "GuiControl",
                "GuiControlGet",
                "GuiDropFiles (label)",
                "GuiEscape (label)",
                "GuiSize (label)",
                "hexadecimal format",
                "hibernate or suspend",
                "hidden text",
                "hidden windows",
                "HKEY_CLASSES_ROOT",
                "HKEY_CURRENT_CONFIG",
                "HKEY_CURRENT_USER",
                "HKEY_LOCAL_MACHINE",
                "HKEY_USERS",
                "hook",
                "Hotkey",
                "Hotkey command",
                "Hotkey controls (GUI)",
                "Hotkey, ListHotkeys",
                "Hotkey, other features",
                "HotkeyInterval",
                "HotkeyModifierTimeout",
                "hotstrings and auto-replace",
                "HTML color names",
                "HWND (of a control)",
                "HWND (of a window)",
                "icon, changing",
                "ID number for a window",
                "If",
                "If (expression)",
                "If var [not] between Low and High",
                "If var [not] in/contains MatchList",
                "If var is [not] type",
                "IfEqual",
                "IfExist",
                "IfGreater",
                "IfGreaterOrEqual",
                "IfInString",
                "IfLess",
                "IfLessOrEqual",
                "IfMsgBox",
                "IfNotEqual",
                "IfNotExist",
                "IfNotInString",
                "IfWinActive",
                "IfWinExist",
                "IfWinNotActive",
                "IfWinNotExist",
                "IL_Add()",
                "IL_Create()",
                "IL_Destroy()",
                "Image Lists (GUI)",
                "ImageSearch",
                "Include",
                "infrared remote controls",
                "IniDelete",
                "IniRead",
                "IniWrite",
                "Input",
                "InputBox",
                "InsertInteger -&gt; NumPut()",
                "Install",
                "Installer Options",
                "InstallKeybdHook",
                "InstallMouseHook",
                "InStr()",
                "integer (check if it is one)",
                "integer (SetFormat)",
                "Interrupt",
                "IsLabel()",
                "Join (continuation sections)",
                "Joystick",
                "JScript, embedded/inline",
                "key list (keyboard, mouse, joystick)",
                "key state",
                "keyboard hook",
                "KeyHistory",
                "keystrokes, sending",
                "KeyWait",
                "labels",
                "last found window",
                "LeftClick",
                "LeftClickDrag",
                "length of a string",
                "libraries of functions",
                "license",
                "line continuation",
                "ListBox controls (GUI)",
                "ListHotkeys",
                "ListLines",
                "ListVars",
                "ListView controls (GUI)",
                "ListView, getting text from",
                "Ln()",
                "lnk (link/shortcut) file",
                "local variables",
                "Locale",
                "Log()",
                "logarithm, log()",
                "logoff",
                "long file name (converting to)",
                "Loop",
                "Loop (registry)",
                "Loop (while)",
                "Loop, FilePattern",
                "Loop, Parse a string",
                "Loop, Read file contents",
                "lParam",
                "LTrim (continuation sections)",
                "LV_Add()",
                "LV_Delete()",
                "LV_DeleteCol()",
                "LV_GetCount()",
                "LV_GetNext()",
                "LV_GetText()",
                "LV_Insert()",
                "LV_InsertCol()",
                "LV_Modify()",
                "LV_ModifyCol()",
                "LV_SetImageList()",
                "macro",
                "math operations (expressions)",
                "MaxHotkeysPerInterval",
                "MaxThreads",
                "MaxThreadsBuffer",
                "MaxThreadsPerHotkey",
                "Menu",
                "Menu Bar (GUI)",
                "message list (WM_*)",
                "messages, receiving",
                "messages, sending",
                "Mod()",
                "modal (always on top)",
                "modulo, mod()",
                "MonthCal controls (GUI)",
                "mouse hook",
                "mouse speed",
                "mouse wheel",
                "MouseClick",
                "MouseClickDrag",
                "MouseGetPos",
                "MouseMove",
                "move a window",
                "move file",
                "move folder/directory",
                "MsgBox",
                "multiply",
                "mute (changing it)",
                "NoTimers",
                "NoTrayIcon",
                "number",
                "number format",
                "NumGet",
                "NumPut",
                "OnClipboardChange (label)",
                "OnExit",
                "OnMessage()",
                "open file",
                "operators in expressions",
                "OutputDebug",
                "OwnDialogs (GUI)",
                "Owner of a GUI window",
                "parameters passed into a script",
                "parse a string (Loop)",
                "parse a string (StringSplit)",
                "Pause",
                "performance of scripts",
                "Picture controls (GUI)",
                "PID (Process ID)",
                "PixelGetColor",
                "PixelSearch",
                "play a sound or video file",
                "PostMessage",
                "power (exponentiation)",
                "prefix and suffix keys",
                "print a file",
                "priority of a process",
                "priority of a thread",
                "Process",
                "ProgramFiles",
                "Progress",
                "Progress controls (GUI)",
                "properties of a file or folder",
                "quit script",
                "Radio controls (GUI)",
                "Random",
                "read file",
                "READONLY",
                "reboot",
                "REG_BINARY",
                "REG_DWORD",
                "REG_EXPAND_SZ",
                "REG_MULTI_SZ",
                "REG_SZ",
                "RegDelete",
                "RegEx: Quick Reference",
                "RegEx: SetTitleMatchMode RegEx",
                "RegExMatch()",
                "RegExReplace()",
                "RegisterCallback()",
                "registry loop",
                "RegRead",
                "regular expressions: Quick Reference",
                "regular expressions: RegExMatch()",
                "regular expressions: RegExReplace()",
                "regular expressions: SetTitleMatchMode RegEx",
                "RegWrite",
                "Reload",
                "remap joystick",
                "remap keys or mouse buttons",
                "remote controls, hand-held",
                "remove folder/directory",
                "rename file",
                "Repeat",
                "resize a window",
                "restart the computer",
                "Return",
                "RGB color names",
                "RGB colors",
                "RightClick",
                "RightClickDrag",
                "Round()",
                "rounding a number",
                "Run",
                "RunAs",
                "RunWait",
                "SB_SetIcon()",
                "SB_SetParts()",
                "SB_SetText()",
                "scan code",
                "scientific notation",
                "Script Showcase",
                "Scripts",
                "select file",
                "select folder",
                "Send",
                "SendEvent",
                "sending data between scripts",
                "SendInput",
                "SendMessage",
                "SendMode",
                "SendPlay",
                "SendRaw",
                "SetBatchLines",
                "SetCapsLockState",
                "SetControlDelay",
                "SetDefaultMouseSpeed",
                "SetEnv",
                "SetFormat",
                "SetKeyDelay",
                "SetMouseDelay",
                "SetNumLockState",
                "SetScrollLockState",
                "SetStoreCapslockMode",
                "SetTimer",
                "SetTitleMatchMode",
                "SetWinDelay",
                "SetWorkingDir",
                "short file name (8.3 format)",
                "short-circuit boolean evaluation",
                "shortcut file",
                "Shutdown",
                "Silent Install/Uninstall",
                "Sin()",
                "SingleInstance",
                "size of a file/folder",
                "size of a window",
                "Sleep",
                "Slider controls (GUI)",
                "Sort",
                "SoundBeep",
                "SoundGet",
                "SoundGetWaveVolume",
                "SoundPlay",
                "SoundSet",
                "SoundSetWaveVolume",
                "space",
                "speed of a script",
                "spinner control (GUI)",
                "SplashImage",
                "SplashTextOff",
                "SplashTextOn",
                "SplitPath",
                "splitting long lines",
                "Sqrt()",
                "standard library",
                "standard output (stdout)",
                "static variables",
                "StatusBar controls (GUI)",
                "StatusBarGetText",
                "StatusBarWait",
                "string (search for)",
                "string: InStr()",
                "string: SubStr()",
                "StringCaseSense",
                "StringGetPos",
                "StringLeft",
                "StringLen",
                "StringLower",
                "StringMid",
                "StringReplace",
                "StringRight",
                "StringSplit",
                "StringTrimLeft",
                "StringTrimRight",
                "StringUpper",
                "StrLen()",
                "structures, via DllCall",
                "styles for GUI command",
                "SubStr()",
                "subtract",
                "Suspend",
                "suspend or hibernate",
                "SysGet",
                "Tab controls (GUI)",
                "Tan()",
                "terminate a window",
                "terminate script",
                "ternary operator (?:)",
                "Text controls (GUI)",
                "Thread",
                "threads",
                "time",
                "Timer (timed subroutines)",
                "times and dates (compare)",
                "times and dates (math)",
                "times and dates (of files)",
                "title of a window",
                "ToolTip",
                "Transform",
                "transparency of a window",
                "tray icon",
                "tray menu (customizing)",
                "TrayTip",
                "TreeView controls (GUI)",
                "Trim",
                "Tutorial",
                "TV_Add()",
                "TV_Delete()",
                "TV_Get()",
                "TV_GetChild()",
                "TV_GetCount()",
                "TV_GetNext()",
                "TV_GetParent()",
                "TV_GetPrev()",
                "TV_GetSelection()",
                "TV_GetText()",
                "TV_Modify()",
                "Unicode text and clipboard",
                "UpDown controls (GUI)",
                "URLDownloadToFile",
                "UseHook",
                "user (run as a different user)",
                "user library",
                "variables, assigning to",
                "variables, built-in",
                "variables, comparing them",
                "variables, ListVars",
                "variables, MAIN",
                "variables, type of data",
                "variants (duplicate hotkeys and hotstrings)",
                "VarSetCapacity()",
                "VBScript, embedded/inline",
                "version of a file",
                "virtual key",
                "volume (changing it)",
                "wait (sleep)",
                "wait for a key to be released or pressed",
                "Wheel hotkeys for mouse",
                "Wheel, simulating rotation",
                "While-loop",
                "whitespace",
                "wildcards (for files &amp; folders)",
                "WinActivate",
                "WinActivateBottom",
                "WinActivateForce",
                "WinActive()",
                "Winamp automation",
                "WinClose",
                "Windows Messages",
                "WinExist()",
                "WinGet",
                "WinGetActiveStats",
                "WinGetActiveTitle",
                "WinGetClass",
                "WinGetPos",
                "WinGetText",
                "WinGetTitle",
                "WinHide",
                "WinKill",
                "WinLIRC, connecting to",
                "WinMaximize",
                "WinMenuSelectItem",
                "WinMinimize",
                "WinMinimizeAll",
                "WinMinimizeAllUndo",
                "WinMove",
                "WinRestore",
                "WinSet",
                "WinSetTitle",
                "WinShow",
                "WinSize (via WinMove)",
                "WinWait",
                "WinWaitActive",
                "WinWaitClose",
                "WinWaitNotActive",
                "WM_* (Windows messages)",
                "WM_COPYDATA",
                "working directory",
                "wParam",
                "write file",
                "WS_* (GUI styles)",
                "XButton",
                "YYYYMMDDHH24MISS",
            };
            #endregion

            #region URIs
            public static readonly string[] URIs = new string[] { 
                "docs/commands/_AllowSameLineComments.htm",
                "docs/commands/_ClipboardTimeout.htm",
                "docs/commands/_CommentFlag.htm",
                "docs/commands/_EscapeChar.htm#Delimiter",
                "docs/commands/_EscapeChar.htm#DerefChar",
                "docs/commands/_ErrorStdOut.htm",
                "docs/commands/_EscapeChar.htm",
                "docs/commands/_HotkeyInterval.htm",
                "docs/commands/_HotkeyModifierTimeout.htm",
                "docs/commands/_Hotstring.htm",
                "docs/commands/_IfWinActive.htm",
                "docs/commands/_IfWinActive.htm",
                "docs/commands/_Include.htm",
                "docs/commands/_Include.htm",
                "docs/commands/_InstallKeybdHook.htm",
                "docs/commands/_InstallMouseHook.htm",
                "docs/commands/_KeyHistory.htm",
                "docs/Scripts.htm#LTrim",
                "docs/commands/_MaxHotkeysPerInterval.htm",
                "docs/commands/_MaxMem.htm",
                "docs/commands/_MaxThreads.htm",
                "docs/commands/_MaxThreadsBuffer.htm",
                "docs/commands/_MaxThreadsPerHotkey.htm",
                "docs/commands/_NoEnv.htm",
                "docs/commands/_NoTrayIcon.htm",
                "docs/commands/_Persistent.htm",
                "docs/commands/_SingleInstance.htm",
                "docs/commands/_UseHook.htm",
                "docs/commands/_WinActivateForce.htm",
                "docs/commands/SetExpression.htm",
                "docs/commands/Send.htm#blind",
                "docs/Variables.htm#AhkPath",
                "docs/Variables.htm#AhkVersion",
                "docs/Variables.htm#AppData",
                "docs/Variables.htm#AppDataCommon",
                "docs/Variables.htm#AutoTrim",
                "docs/Variables.htm#BatchLines",
                "docs/Variables.htm#Caret",
                "docs/Variables.htm#Caret",
                "docs/Variables.htm#ComputerName",
                "docs/Variables.htm#ControlDelay",
                "docs/Variables.htm#Cursor",
                "docs/Variables.htm#DD",
                "docs/Variables.htm#DDDD",
                "docs/Variables.htm#DDDD",
                "docs/Variables.htm#DefaultMouseSpeed",
                "docs/Variables.htm#Desktop",
                "docs/Variables.htm#DesktopCommon",
                "docs/Variables.htm#DetectHiddenText",
                "docs/Variables.htm#DetectHiddenWindows",
                "docs/Variables.htm#EndChar",
                "docs/Variables.htm#EventInfo",
                "docs/Variables.htm#ExitReason",
                "docs/Variables.htm#FormatFloat",
                "docs/Variables.htm#FormatInteger",
                "docs/Variables.htm#Gui",
                "docs/Variables.htm#GuiControl",
                "docs/Variables.htm#GuiControlEvent",
                "docs/Variables.htm#GuiEvent",
                "docs/Variables.htm#GuiWidth",
                "docs/Variables.htm#GuiWidth",
                "docs/Variables.htm#GuiX",
                "docs/Variables.htm#GuiY",
                "docs/Variables.htm#Hour",
                "docs/Variables.htm#IconFile",
                "docs/Variables.htm#IconHidden",
                "docs/Variables.htm#IconNumber",
                "docs/Variables.htm#IconTip",
                "docs/commands/Loop.htm",
                "docs/Variables.htm#IPAddress",
                "docs/Variables.htm#IsAdmin",
                "docs/Variables.htm#IsPaused",
                "docs/Variables.htm#IsCompiled",
                "docs/Variables.htm#IsCritical",
                "docs/Variables.htm#IsSuspended",
                "docs/Variables.htm#KeyDelay",
                "docs/Variables.htm#Language",
                "docs/misc/Languages.htm",
                "docs/Variables.htm#LastError",
                "docs/Variables.htm#LineFile",
                "docs/Variables.htm#LineNumber",
                "docs/commands/LoopParse.htm#LoopField",
                "docs/commands/LoopFile.htm#LoopFileAttrib",
                "docs/commands/LoopFile.htm#LoopFileDir",
                "docs/commands/LoopFile.htm#LoopFileExt",
                "docs/commands/LoopFile.htm#LoopFileFullPath",
                "docs/commands/LoopFile.htm#LoopFileLongPath",
                "docs/commands/LoopFile.htm#LoopFileName",
                "docs/commands/LoopFile.htm#LoopFileShortName",
                "docs/commands/LoopFile.htm#LoopFileShortPath",
                "docs/commands/LoopFile.htm#LoopFileSize",
                "docs/commands/LoopFile.htm#LoopFileSizeKB",
                "docs/commands/LoopFile.htm#LoopFileSizeMB",
                "docs/commands/LoopFile.htm#LoopFileTimeAccessed",
                "docs/commands/LoopFile.htm#LoopFileTimeCreated",
                "docs/commands/LoopFile.htm#LoopFileTimeModified",
                "docs/commands/LoopReadFile.htm#LoopReadLine",
                "docs/commands/LoopReg.htm",
                "docs/commands/LoopReg.htm",
                "docs/commands/LoopReg.htm",
                "docs/commands/LoopReg.htm",
                "docs/commands/LoopReg.htm",
                "docs/Variables.htm#DD",
                "docs/Variables.htm#Min",
                "docs/Variables.htm#MM",
                "docs/Variables.htm#MMM",
                "docs/Variables.htm#MMMM",
                "docs/Variables.htm#MM",
                "docs/Variables.htm#MouseDelay",
                "docs/Variables.htm#MSec",
                "docs/Variables.htm#MyDocuments",
                "docs/Variables.htm#Now",
                "docs/Variables.htm#NowUTC",
                "docs/Variables.htm#BatchLines",
                "docs/Variables.htm#OSType",
                "docs/Variables.htm#OSVersion",
                "docs/Variables.htm#PriorHotkey",
                "docs/Variables.htm#ProgramFiles",
                "docs/Variables.htm#Programs",
                "docs/Variables.htm#ProgramsCommon",
                "docs/Variables.htm#Screen",
                "docs/Variables.htm#Screen",
                "docs/Variables.htm#ScriptDir",
                "docs/Variables.htm#ScriptFullPath",
                "docs/Variables.htm#ScriptName",
                "docs/Variables.htm#Sec",
                "docs/Variables.htm#Space",
                "docs/Variables.htm#StartMenu",
                "docs/Variables.htm#StartMenuCommon",
                "docs/Variables.htm#Startup",
                "docs/Variables.htm#StartupCommon",
                "docs/Variables.htm#StringCaseSense",
                "docs/Variables.htm#Tab",
                "docs/Variables.htm#Temp",
                "docs/Variables.htm#ThisFunc",
                "docs/Variables.htm#ThisHotkey",
                "docs/Variables.htm#ThisLabel",
                "docs/Variables.htm#ThisMenu",
                "docs/Variables.htm#ThisMenuItem",
                "docs/Variables.htm#ThisMenuItemPos",
                "docs/Variables.htm#TickCount",
                "docs/Variables.htm#TimeIdle",
                "docs/Variables.htm#TimeIdlePhysical",
                "docs/Variables.htm#TimeSincePriorHotkey",
                "docs/Variables.htm#TimeSinceThisHotkey",
                "docs/Variables.htm#TitleMatchMode",
                "docs/Variables.htm#TitleMatchModeSpeed",
                "docs/Variables.htm#UserName",
                "docs/Variables.htm#WDay",
                "docs/Variables.htm#WinDelay",
                "docs/Variables.htm#WinDir",
                "docs/Variables.htm#WorkingDir",
                "docs/Variables.htm#YDay",
                "docs/Variables.htm#YYYY",
                "docs/Variables.htm#YWeek",
                "docs/Variables.htm#YYYY",
                "docs/Hotstrings.htm",
                "docs/Functions.htm#Abs",
                "docs/Functions.htm#Abs",
                "docs/misc/acknowledgements.htm",
                "docs/Functions.htm#ACos",
                "docs/commands/WinActivate.htm",
                "docs/commands/EnvAdd.htm",
                "docs/Variables.htm#amp",
                "docs/Variables.htm#RequireAdmin",
                "docs/LastFoundWindow.htm#class",
                "docs/LastFoundWindow.htm#group",
                "docs/LastFoundWindow.htm#id",
                "docs/LastFoundWindow.htm#pid",
                "docs/Scripts.htm#ahk2exe",
                "docs/commands/_AllowSameLineComments.htm",
                "docs/commands/IfIs.htm",
                "docs/commands/IfIs.htm",
                "docs/Hotkeys.htm#AltGr",
                "docs/Hotkeys.htm#alttab",
                "docs/commands/WinSet.htm",
                "docs/commands/FileAppend.htm",
                "docs/misc/Arrays.htm",
                "docs/Functions.htm#Asc",
                "docs/commands/Transform.htm",
                "docs/Functions.htm#ASin",
                "docs/Variables.htm#AssignOp",
                "docs/Functions.htm#ATan",
                "docs/commands/FileGetAttrib.htm",
                "docs/Scripts.htm",
                "docs/AutoIt2Users.htm",
                "docs/Hotstrings.htm",
                "docs/misc/Macros.htm",
                "docs/commands/AutoTrim.htm",
                "docs/commands/TrayTip.htm",
                "docs/commands/SoundBeep.htm",
                "docs/commands/IfBetween.htm",
                "docs/Variables.htm#bitwise",
                "docs/commands/Send.htm#blind",
                "docs/commands/BlockInput.htm",
                "docs/commands/Block.htm",
                "docs/commands/Break.htm",
                "docs/commands/_MaxThreadsBuffer.htm",
                "docs/Functions.htm#BuiltIn",
                "docs/Variables.htm#BuiltIn",
                "docs/commands/GuiControls.htm#Button",
                "docs/KeyList.htm",
                "docs/commands/GetKeyState.htm",
                "docs/Functions.htm#ByRef",
                "docs/commands/RegisterCallback.htm",
                "docs/commands/StringCaseSense.htm",
                "docs/Functions.htm#Ceil",
                "docs/ChangeLogHelp.htm",
                "docs/commands/GuiControls.htm#Checkbox",
                "docs/commands/FileSelectFile.htm",
                "docs/commands/FileSelectFolder.htm",
                "docs/Functions.htm#Chr",
                "docs/commands/WinGetClass.htm",
                "docs/commands/Click.htm",
                "docs/misc/Clipboard.htm",
                "docs/misc/Clipboard.htm#ClipboardAll",
                "docs/commands/ClipWait.htm",
                "docs/commands/WinClose.htm",
                "docs/misc/CLSID-List.htm",
                "docs/commands/Progress.htm#colors",
                "docs/commands/PixelSearch.htm",
                "docs/commands/DllCall.htm#COM",
                "docs/commands/GuiControls.htm#ComboBox",
                "docs/Variables.htm#comma",
                "docs/Scripts.htm#cmd",
                "docs/commands.htm",
                "docs/commands/_CommentFlag.htm",
                "docs/Scripts.htm",
                "docs/Scripts.htm#ahk2exe",
                "docs/commands/DllCall.htm#COM",
                "docs/Variables.htm#ComSpec",
                "docs/Variables.htm#concat",
                "docs/Scripts.htm#continuation",
                "docs/commands/Gui.htm#GuiContextMenu",
                "docs/Scripts.htm#continuation",
                "docs/commands/Continue.htm",
                "docs/commands/Control.htm",
                "docs/commands/ControlClick.htm",
                "docs/commands/ControlFocus.htm",
                "docs/commands/ControlGet.htm",
                "docs/commands/ControlGetFocus.htm",
                "docs/commands/ControlGetPos.htm",
                "docs/commands/ControlGetText.htm",
                "docs/commands/ControlMove.htm",
                "docs/commands/ControlSend.htm",
                "docs/commands/ControlSend.htm",
                "docs/commands/ControlSetText.htm",
                "docs/AutoIt2Users.htm",
                "docs/Scripts.htm#ahk2exe",
                "docs/commands/CoordMode.htm",
                "docs/commands/CoordMode.htm",
                "docs/commands/FileCopy.htm",
                "docs/commands/FileCopyDir.htm",
                "docs/Functions.htm#Cos",
                "docs/commands/FileAppend.htm",
                "docs/commands/FileCreateDir.htm",
                "docs/commands/Critical.htm",
                "docs/commands/SetWorkingDir.htm",
                "docs/misc/Threads.htm",
                "docs/Variables.htm#Cursor",
                "docs/commands/EnvSub.htm",
                "docs/commands/EnvAdd.htm",
                "docs/commands/FileSetTime.htm",
                "docs/commands/GuiControls.htm#DateTime",
                "docs/commands/OutputDebug.htm",
                "docs/Scripts.htm#debug",
                "docs/commands/SetFormat.htm",
                "docs/Scripts.htm#exe2ahk",
                "docs/commands/FileDelete.htm",
                "docs/commands/FileRemoveDir.htm",
                "docs/commands/_EscapeChar.htm",
                "docs/commands/_EscapeChar.htm",
                "docs/commands/DetectHiddenText.htm",
                "docs/commands/DetectHiddenWindows.htm",
                "docs/commands/FileSelectFile.htm",
                "docs/commands/FileSelectFolder.htm",
                "docs/commands/InputBox.htm",
                "docs/commands/MsgBox.htm",
                "docs/commands/IfIs.htm",
                "docs/commands/DriveSpaceFree.htm",
                "docs/Variables.htm#divide",
                "docs/commands/DllCall.htm",
                "docs/commands/URLDownloadToFile.htm",
                "docs/commands/Gui.htm#GuiDropFiles",
                "docs/commands/MouseClickDrag.htm",
                "docs/commands/Drive.htm",
                "docs/commands/DriveGet.htm",
                "docs/commands/DriveSpaceFree.htm",
                "docs/commands/GuiControls.htm#DropDownList",
                "docs/commands/Edit.htm",
                "docs/commands/GuiControls.htm#Edit",
                "docs/commands/Else.htm",
                "docs/commands/Loop.htm",
                "docs/commands/EnvAdd.htm",
                "docs/commands/EnvDiv.htm",
                "docs/commands/EnvGet.htm",
                "docs/Variables.htm#env",
                "docs/commands/EnvSet.htm",
                "docs/commands/EnvMult.htm",
                "docs/commands/EnvSet.htm",
                "docs/commands/EnvSub.htm",
                "docs/commands/EnvUpdate.htm",
                "docs/misc/ErrorLevel.htm",
                "docs/commands/_ErrorStdOut.htm",
                "docs/commands/_EscapeChar.htm",
                "docs/commands/_EscapeChar.htm",
                "docs/Scripts.htm#exe2ahk",
                "docs/commands/Exit.htm",
                "docs/commands/ExitApp.htm",
                "docs/Functions.htm#Exp",
                "docs/Variables.htm#Expressions",
                "docs/Functions.htm#NumGet",
                "docs/FAQ.htm",
                "docs/commands/FileSetAttrib.htm",
                "docs/commands/IfExist.htm",
                "docs/commands/LoopFile.htm",
                "docs/commands/FileAppend.htm",
                "docs/commands/LoopReadFile.htm",
                "docs/commands/FileAppend.htm",
                "docs/commands/FileAppend.htm",
                "docs/commands/FileCopy.htm",
                "docs/commands/FileCopyDir.htm",
                "docs/commands/FileCreateDir.htm",
                "docs/commands/FileCreateShortcut.htm",
                "docs/commands/FileDelete.htm",
                "docs/Functions.htm#FileExist",
                "docs/commands/FileGetAttrib.htm",
                "docs/commands/FileGetShortcut.htm",
                "docs/commands/FileGetSize.htm",
                "docs/commands/FileGetTime.htm",
                "docs/commands/FileGetVersion.htm",
                "docs/commands/FileInstall.htm",
                "docs/commands/FileMove.htm",
                "docs/commands/FileMoveDir.htm",
                "docs/commands/FileRead.htm",
                "docs/commands/FileReadLine.htm",
                "docs/commands/FileRecycle.htm",
                "docs/commands/FileRecycleEmpty.htm",
                "docs/commands/FileRemoveDir.htm",
                "docs/commands/FileSelectFile.htm",
                "docs/commands/FileSelectFolder.htm",
                "docs/commands/FileSetAttrib.htm",
                "docs/commands/FileSetTime.htm",
                "docs/commands/IfExist.htm",
                "docs/commands/StringGetPos.htm",
                "docs/commands/IfWinExist.htm",
                "docs/commands/IfIs.htm",
                "docs/commands/SetFormat.htm",
                "docs/Functions.htm#Floor",
                "docs/commands/ControlFocus.htm",
                "docs/commands/FileCopyDir.htm",
                "docs/commands/FileCreateDir.htm",
                "docs/commands/FileMoveDir.htm",
                "docs/commands/FileRemoveDir.htm",
                "docs/commands/FileSelectFolder.htm",
                "docs/misc/FontsStandard.htm",
                "docs/commands/SetFormat.htm",
                "docs/commands/FormatTime.htm",
                "docs/commands/DriveSpaceFree.htm",
                "docs/commands/FileAppend.htm#FTP",
                "docs/Functions.htm",
                "docs/Functions.htm#lib",
                "docs/commands/PixelSearch.htm",
                "docs/commands/GetKeyState.htm",
                "docs/Functions.htm#GetKeyState",
                "docs/commands/Gui.htm#label",
                "docs/Functions.htm#Global",
                "docs/commands/Gosub.htm",
                "docs/commands/Goto.htm",
                "docs/commands/GroupActivate.htm",
                "docs/commands/GroupAdd.htm",
                "docs/commands/GuiControls.htm#GroupBox",
                "docs/commands/GroupClose.htm",
                "docs/commands/GroupDeactivate.htm",
                "docs/commands/Gui.htm",
                "docs/commands/GuiControls.htm",
                "docs/misc/Styles.htm",
                "docs/commands/Gui.htm#GuiClose",
                "docs/commands/Gui.htm#GuiContextMenu",
                "docs/commands/GuiControl.htm",
                "docs/commands/GuiControlGet.htm",
                "docs/commands/Gui.htm#GuiDropFiles",
                "docs/commands/Gui.htm#GuiEscape",
                "docs/commands/Gui.htm#GuiSize",
                "docs/commands/SetFormat.htm",
                "docs/commands/Shutdown.htm#Suspend",
                "docs/commands/DetectHiddenText.htm",
                "docs/commands/DetectHiddenWindows.htm",
                "docs/commands/RegRead.htm",
                "docs/commands/RegRead.htm",
                "docs/commands/RegRead.htm",
                "docs/commands/RegRead.htm",
                "docs/commands/RegRead.htm",
                "docs/commands/_InstallKeybdHook.htm",
                "docs/Hotkeys.htm",
                "docs/commands/Hotkey.htm",
                "docs/commands/GuiControls.htm#Hotkey",
                "docs/commands/ListHotkeys.htm",
                "docs/HotkeyFeatures.htm",
                "docs/commands/_HotkeyInterval.htm",
                "docs/commands/_HotkeyModifierTimeout.htm",
                "docs/Hotstrings.htm",
                "docs/commands/Progress.htm#colors",
                "docs/commands/ControlGet.htm#Hwnd",
                "docs/LastFoundWindow.htm#id",
                "docs/commands/Menu.htm#Icon",
                "docs/commands/WinGet.htm",
                "docs/commands/IfEqual.htm",
                "docs/commands/IfExpression.htm",
                "docs/commands/IfBetween.htm",
                "docs/commands/IfIn.htm",
                "docs/commands/IfIs.htm",
                "docs/commands/IfEqual.htm",
                "docs/commands/IfExist.htm",
                "docs/commands/IfEqual.htm",
                "docs/commands/IfEqual.htm",
                "docs/commands/IfInString.htm",
                "docs/commands/IfEqual.htm",
                "docs/commands/IfEqual.htm",
                "docs/commands/IfMsgBox.htm",
                "docs/commands/IfEqual.htm",
                "docs/commands/IfExist.htm",
                "docs/commands/IfInString.htm",
                "docs/commands/IfWinActive.htm",
                "docs/commands/IfWinExist.htm",
                "docs/commands/IfWinActive.htm",
                "docs/commands/IfWinExist.htm",
                "docs/commands/ListView.htm#IL_Add",
                "docs/commands/ListView.htm#IL_Create",
                "docs/commands/ListView.htm#IL_Destroy",
                "docs/commands/ListView.htm#IL",
                "docs/commands/ImageSearch.htm",
                "docs/commands/_Include.htm",
                "docs/scripts/WinLIRC.htm",
                "docs/commands/IniDelete.htm",
                "docs/commands/IniRead.htm",
                "docs/commands/IniWrite.htm",
                "docs/commands/Input.htm",
                "docs/commands/InputBox.htm",
                "docs/Functions.htm#NumPut",
                "docs/commands/FileInstall.htm",
                "docs/Scripts.htm#install",
                "docs/commands/_InstallKeybdHook.htm",
                "docs/commands/_InstallMouseHook.htm",
                "docs/Functions.htm#InStr",
                "docs/commands/IfIs.htm",
                "docs/commands/SetFormat.htm",
                "docs/commands/Thread.htm",
                "docs/Functions.htm#IsLabel",
                "docs/Scripts.htm#Join",
                "docs/KeyList.htm",
                "docs/commands/DllCall.htm#COM",
                "docs/KeyList.htm",
                "docs/commands/GetKeyState.htm",
                "docs/commands/_InstallKeybdHook.htm",
                "docs/commands/KeyHistory.htm",
                "docs/commands/Send.htm",
                "docs/commands/KeyWait.htm",
                "docs/commands/Gosub.htm",
                "docs/LastFoundWindow.htm",
                "docs/commands/Click.htm",
                "docs/commands/MouseClickDrag.htm",
                "docs/commands/StringLen.htm",
                "docs/Functions.htm#lib",
                "docs/license.htm",
                "docs/Scripts.htm#continuation",
                "docs/commands/GuiControls.htm#ListBox",
                "docs/commands/ListHotkeys.htm",
                "docs/commands/ListLines.htm",
                "docs/commands/ListVars.htm",
                "docs/commands/ListView.htm",
                "docs/commands/ControlGet.htm#List",
                "docs/Functions.htm#Ln",
                "docs/commands/FileCreateShortcut.htm",
                "docs/Functions.htm#Locals",
                "docs/commands/StringCaseSense.htm#Locale",
                "docs/Functions.htm#Log",
                "docs/Functions.htm#Log",
                "docs/commands/Shutdown.htm",
                "docs/commands/LoopFile.htm#LoopFileLongPath",
                "docs/commands/Loop.htm",
                "docs/commands/LoopReg.htm",
                "docs/commands/While.htm",
                "docs/commands/LoopFile.htm",
                "docs/commands/LoopParse.htm",
                "docs/commands/LoopReadFile.htm",
                "docs/commands/PostMessage.htm",
                "docs/Scripts.htm#LTrim",
                "docs/commands/ListView.htm#LV_Add",
                "docs/commands/ListView.htm#LV_Delete",
                "docs/commands/ListView.htm#LV_DeleteCol",
                "docs/commands/ListView.htm#LV_GetCount",
                "docs/commands/ListView.htm#LV_GetNext",
                "docs/commands/ListView.htm#LV_GetText",
                "docs/commands/ListView.htm#LV_Insert",
                "docs/commands/ListView.htm#LV_InsertCol",
                "docs/commands/ListView.htm#LV_Modify",
                "docs/commands/ListView.htm#LV_ModifyCol",
                "docs/commands/ListView.htm#LV_SetImageList",
                "docs/misc/Macros.htm",
                "docs/Variables.htm#Expressions",
                "docs/commands/_MaxHotkeysPerInterval.htm",
                "docs/commands/_MaxThreads.htm",
                "docs/commands/_MaxThreadsBuffer.htm",
                "docs/commands/_MaxThreadsPerHotkey.htm",
                "docs/commands/Menu.htm",
                "docs/commands/Gui.htm#Menu",
                "docs/misc/SendMessageList.htm",
                "docs/commands/OnMessage.htm",
                "docs/commands/PostMessage.htm",
                "docs/Functions.htm#Mod",
                "docs/commands/MsgBox.htm",
                "docs/Functions.htm#Mod",
                "docs/commands/GuiControls.htm#MonthCal",
                "docs/commands/_InstallMouseHook.htm",
                "docs/commands/SetDefaultMouseSpeed.htm",
                "docs/commands/Click.htm",
                "docs/commands/MouseClick.htm",
                "docs/commands/MouseClickDrag.htm",
                "docs/commands/MouseGetPos.htm",
                "docs/commands/MouseMove.htm",
                "docs/commands/WinMove.htm",
                "docs/commands/FileMove.htm",
                "docs/commands/FileMoveDir.htm",
                "docs/commands/MsgBox.htm",
                "docs/commands/EnvMult.htm",
                "docs/commands/SoundSet.htm",
                "docs/commands/Thread.htm",
                "docs/commands/_NoTrayIcon.htm",
                "docs/commands/IfIs.htm",
                "docs/commands/SetFormat.htm",
                "docs/Functions.htm#NumGet",
                "docs/Functions.htm#NumPut",
                "docs/misc/Clipboard.htm#OnClipboardChange",
                "docs/commands/OnExit.htm",
                "docs/commands/OnMessage.htm",
                "docs/commands/FileReadLine.htm",
                "docs/Variables.htm#Operators",
                "docs/commands/OutputDebug.htm",
                "docs/commands/Gui.htm#OwnDialogs",
                "docs/commands/Gui.htm#Owner",
                "docs/Scripts.htm",
                "docs/commands/LoopParse.htm",
                "docs/commands/StringSplit.htm",
                "docs/commands/Pause.htm",
                "docs/misc/Performance.htm",
                "docs/commands/GuiControls.htm#Picture",
                "docs/commands/Process.htm",
                "docs/commands/PixelGetColor.htm",
                "docs/commands/PixelSearch.htm",
                "docs/commands/SoundPlay.htm",
                "docs/commands/PostMessage.htm",
                "docs/Variables.htm#pow",
                "docs/Hotkeys.htm",
                "docs/commands/Run.htm",
                "docs/commands/Process.htm",
                "docs/commands/Thread.htm",
                "docs/commands/Process.htm",
                "docs/Variables.htm#ProgramFiles",
                "docs/commands/Progress.htm",
                "docs/commands/GuiControls.htm#Progress",
                "docs/commands/Run.htm",
                "docs/commands/ExitApp.htm",
                "docs/commands/GuiControls.htm#Radio",
                "docs/commands/Random.htm",
                "docs/commands/FileReadLine.htm",
                "docs/commands/FileGetAttrib.htm",
                "docs/commands/Shutdown.htm",
                "docs/commands/RegRead.htm",
                "docs/commands/RegRead.htm",
                "docs/commands/RegRead.htm",
                "docs/commands/RegRead.htm",
                "docs/commands/RegRead.htm",
                "docs/commands/RegDelete.htm",
                "docs/misc/RegEx-QuickRef.htm",
                "docs/commands/SetTitleMatchMode.htm#RegEx",
                "docs/commands/RegExMatch.htm",
                "docs/commands/RegExReplace.htm",
                "docs/commands/RegisterCallback.htm",
                "docs/commands/LoopReg.htm",
                "docs/commands/RegRead.htm",
                "docs/misc/RegEx-QuickRef.htm",
                "docs/commands/RegExMatch.htm",
                "docs/commands/RegExReplace.htm",
                "docs/commands/SetTitleMatchMode.htm#RegEx",
                "docs/commands/RegWrite.htm",
                "docs/commands/Reload.htm",
                "docs/misc/RemapJoystick.htm",
                "docs/misc/Remap.htm",
                "docs/scripts/WinLIRC.htm",
                "docs/commands/FileRemoveDir.htm",
                "docs/commands/FileMove.htm",
                "docs/commands/Loop.htm",
                "docs/commands/WinMove.htm",
                "docs/commands/Shutdown.htm",
                "docs/commands/Return.htm",
                "docs/commands/Progress.htm#colors",
                "docs/commands/PixelGetColor.htm",
                "docs/commands/Click.htm",
                "docs/commands/MouseClickDrag.htm",
                "docs/Functions.htm#Round",
                "docs/Functions.htm#Round",
                "docs/commands/Run.htm",
                "docs/commands/RunAs.htm",
                "docs/commands/Run.htm",
                "docs/commands/GuiControls.htm#SB_SetIcon",
                "docs/commands/GuiControls.htm#SB_SetParts",
                "docs/commands/GuiControls.htm#SB_SetText",
                "docs/commands/Send.htm#vk",
                "docs/commands/SetFormat.htm#sci",
                "docs/scripts/index.htm",
                "docs/Scripts.htm",
                "docs/commands/FileSelectFile.htm",
                "docs/commands/FileSelectFolder.htm",
                "docs/commands/Send.htm",
                "docs/commands/Send.htm#SendEvent",
                "docs/commands/OnMessage.htm#SendString",
                "docs/commands/Send.htm#SendInputDetail",
                "docs/commands/PostMessage.htm",
                "docs/commands/SendMode.htm",
                "docs/commands/Send.htm#SendPlayDetail",
                "docs/commands/Send.htm",
                "docs/commands/SetBatchLines.htm",
                "docs/commands/SetNumScrollCapsLockState.htm",
                "docs/commands/SetControlDelay.htm",
                "docs/commands/SetDefaultMouseSpeed.htm",
                "docs/commands/SetEnv.htm",
                "docs/commands/SetFormat.htm",
                "docs/commands/SetKeyDelay.htm",
                "docs/commands/SetMouseDelay.htm",
                "docs/commands/SetNumScrollCapsLockState.htm",
                "docs/commands/SetNumScrollCapsLockState.htm",
                "docs/commands/SetStoreCapslockMode.htm",
                "docs/commands/SetTimer.htm",
                "docs/commands/SetTitleMatchMode.htm",
                "docs/commands/SetWinDelay.htm",
                "docs/commands/SetWorkingDir.htm",
                "docs/commands/LoopFile.htm#LoopFileShortPath",
                "docs/Functions.htm#ShortCircuit",
                "docs/commands/FileCreateShortcut.htm",
                "docs/commands/Shutdown.htm",
                "docs/Scripts.htm#install",
                "docs/Functions.htm#Sin",
                "docs/commands/_SingleInstance.htm",
                "docs/commands/FileGetSize.htm",
                "docs/commands/WinGetPos.htm",
                "docs/commands/Sleep.htm",
                "docs/commands/GuiControls.htm#Slider",
                "docs/commands/Sort.htm",
                "docs/commands/SoundBeep.htm",
                "docs/commands/SoundGet.htm",
                "docs/commands/SoundGetWaveVolume.htm",
                "docs/commands/SoundPlay.htm",
                "docs/commands/SoundSet.htm",
                "docs/commands/SoundSetWaveVolume.htm",
                "docs/commands/IfIs.htm",
                "docs/commands/SetBatchLines.htm",
                "docs/commands/GuiControls.htm#UpDown",
                "docs/commands/Progress.htm",
                "docs/commands/SplashTextOn.htm",
                "docs/commands/SplashTextOn.htm",
                "docs/commands/SplitPath.htm",
                "docs/Scripts.htm#continuation",
                "docs/Functions.htm#Sqrt",
                "docs/Functions.htm#lib",
                "docs/commands/FileAppend.htm",
                "docs/Functions.htm#static",
                "docs/commands/GuiControls.htm#StatusBar",
                "docs/commands/StatusBarGetText.htm",
                "docs/commands/StatusBarWait.htm",
                "docs/Functions.htm#InStr",
                "docs/Functions.htm#InStr",
                "docs/Functions.htm#SubStr",
                "docs/commands/StringCaseSense.htm",
                "docs/commands/StringGetPos.htm",
                "docs/commands/StringLeft.htm",
                "docs/commands/StringLen.htm",
                "docs/commands/StringLower.htm",
                "docs/commands/StringMid.htm",
                "docs/commands/StringReplace.htm",
                "docs/commands/StringLeft.htm",
                "docs/commands/StringSplit.htm",
                "docs/commands/StringTrimLeft.htm",
                "docs/commands/StringTrimLeft.htm",
                "docs/commands/StringLower.htm",
                "docs/Functions.htm#StrLen",
                "docs/commands/DllCall.htm#struct",
                "docs/misc/Styles.htm",
                "docs/Functions.htm#SubStr",
                "docs/commands/EnvSub.htm",
                "docs/commands/Suspend.htm",
                "docs/commands/Shutdown.htm#Suspend",
                "docs/commands/SysGet.htm",
                "docs/commands/GuiControls.htm#Tab",
                "docs/Functions.htm#Tan",
                "docs/commands/WinKill.htm",
                "docs/commands/ExitApp.htm",
                "docs/Variables.htm#ternary",
                "docs/commands/GuiControls.htm#Text",
                "docs/commands/Thread.htm",
                "docs/misc/Threads.htm",
                "docs/commands/IfIs.htm",
                "docs/commands/SetTimer.htm",
                "docs/commands/EnvSub.htm",
                "docs/commands/EnvAdd.htm",
                "docs/commands/FileSetTime.htm",
                "docs/commands/WinSetTitle.htm",
                "docs/commands/ToolTip.htm",
                "docs/commands/Transform.htm",
                "docs/commands/WinSet.htm",
                "docs/commands/_NoTrayIcon.htm",
                "docs/commands/Menu.htm",
                "docs/commands/TrayTip.htm",
                "docs/commands/TreeView.htm",
                "docs/commands/AutoTrim.htm",
                "docs/Tutorial.htm",
                "docs/commands/TreeView.htm#TV_Add",
                "docs/commands/TreeView.htm#TV_Delete",
                "docs/commands/TreeView.htm#TV_Get",
                "docs/commands/TreeView.htm#TV_GetChild",
                "docs/commands/TreeView.htm#TV_GetCount",
                "docs/commands/TreeView.htm#TV_GetNext",
                "docs/commands/TreeView.htm#TV_GetParent",
                "docs/commands/TreeView.htm#TV_GetPrev",
                "docs/commands/TreeView.htm#TV_GetSelection",
                "docs/commands/TreeView.htm#TV_GetText",
                "docs/commands/TreeView.htm#TV_Modify",
                "docs/commands/Transform.htm",
                "docs/commands/GuiControls.htm#UpDown",
                "docs/commands/URLDownloadToFile.htm",
                "docs/commands/_UseHook.htm",
                "docs/commands/RunAs.htm",
                "docs/Functions.htm#lib",
                "docs/commands/SetEnv.htm",
                "docs/Variables.htm#BuiltIn",
                "docs/commands/IfEqual.htm",
                "docs/commands/ListVars.htm",
                "docs/Variables.htm",
                "docs/commands/IfIs.htm",
                "docs/commands/_IfWinActive.htm#variant",
                "docs/commands/VarSetCapacity.htm",
                "docs/commands/DllCall.htm#COM",
                "docs/commands/FileGetVersion.htm",
                "docs/commands/Send.htm#vk",
                "docs/commands/SoundSet.htm",
                "docs/commands/Sleep.htm",
                "docs/commands/KeyWait.htm",
                "docs/Hotkeys.htm#Wheel",
                "docs/commands/Click.htm",
                "docs/commands/While.htm",
                "docs/commands/AutoTrim.htm",
                "docs/commands/LoopFile.htm",
                "docs/commands/WinActivate.htm",
                "docs/commands/WinActivateBottom.htm",
                "docs/commands/_WinActivateForce.htm",
                "docs/Functions.htm#WinActive",
                "docs/misc/Winamp.htm",
                "docs/commands/WinClose.htm",
                "docs/misc/SendMessageList.htm",
                "docs/Functions.htm#WinExist",
                "docs/commands/WinGet.htm",
                "docs/commands/WinGetActiveStats.htm",
                "docs/commands/WinGetActiveTitle.htm",
                "docs/commands/WinGetClass.htm",
                "docs/commands/WinGetPos.htm",
                "docs/commands/WinGetText.htm",
                "docs/commands/WinGetTitle.htm",
                "docs/commands/WinHide.htm",
                "docs/commands/WinKill.htm",
                "docs/scripts/WinLIRC.htm",
                "docs/commands/WinMaximize.htm",
                "docs/commands/WinMenuSelectItem.htm",
                "docs/commands/WinMinimize.htm",
                "docs/commands/WinMinimizeAll.htm",
                "docs/commands/WinMinimizeAll.htm",
                "docs/commands/WinMove.htm",
                "docs/commands/WinRestore.htm",
                "docs/commands/WinSet.htm",
                "docs/commands/WinSetTitle.htm",
                "docs/commands/WinShow.htm",
                "docs/commands/WinMove.htm",
                "docs/commands/WinWait.htm",
                "docs/commands/WinWaitActive.htm",
                "docs/commands/WinWaitClose.htm",
                "docs/commands/WinWaitActive.htm",
                "docs/misc/SendMessageList.htm",
                "docs/commands/OnMessage.htm#SendString",
                "docs/commands/SetWorkingDir.htm",
                "docs/commands/PostMessage.htm",
                "docs/commands/FileAppend.htm",
                "docs/misc/Styles.htm",
                "docs/commands/Click.htm",
                "docs/commands/FileSetTime.htm#YYYYMMDD",
            };
            #endregion
        }
    }
}